version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: circleci/golang:1.17.1

    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: |
            curl -sL https://install.goreleaser.com/github.com/hadolint/hadolint.sh | bash -s -- -b $(go env GOPATH)/bin v2.7.0
            hadolint Dockerfile

  test-app:
    docker:
      - image: golang:1.17.1

    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: docker:20.10.12

    steps:
      - checkout
      - run:
          name: Build and Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t your-dockerhub-username/karsajobs:latest .
            docker push your-dockerhub-username/karsajobs:latest